;====================================================================
; Processor		: ATmega8515
; Compiler		: AVRASM
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

.include "m8515def.inc"
.def temp = r16
.def count_jadwal = r17
.def libur_flag = r18
.def persiapan = r19
.def count_libur = r20
.def defense_flag = r21

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

;
.org $00
rjmp MAIN
.org $01
rjmp INTERRUPT_LIBUR
.org $02
rjmp INTERRUPT_DEFENSE
.org $0E
rjmp INTERRUPT_SWITCH_JADWAL

;====================================================================
; CODE SEGMENT
;====================================================================

MAIN:
	ldi count_jadwal, 0 ;todo

INIT_STACK:
	ldi temp, low(RAMEND)
	out SPL, temp
	ldi temp, high(RAMEND)
	out SPH, temp

INIT_LED:
	ser temp
	out DDRA, temp
	out DDRB, temp
	out DDRC, temp

INIT_EXT_INTERRUPT:
	ldi temp, 0b00001111 
	out MCUCR,temp
	ldi temp, 0b11000000 
	out GICR,temp

INIT_INT_INTERRUPT:
	ldi temp, (1 << CS02) | (1 << CS00)
	out TCCR0, temp
	ldi temp, (1 << TOV0) | (1 << OCF0)
	out TIFR, temp
	ldi temp, (1 << OCIE0)
	out TIMSK, temp
	ldi temp, 128
	out OCR0, temp
	sei

CHECK_STATUS:
	cpi defense_flag, 1
	breq DEFENSE
	sbrs libur_flag, 0
	rjmp CHECK_JADWAL
    cpi count_libur, 0
    breq NORMAL
	rjmp LIBUR

NORMAL:
	clr libur_flag
    rjmp CHECK_JADWAL

CHECK_JADWAL:
	cpi count_jadwal, 1
	breq JADWAL_02
	brlo JADWAL_01
	brne JADWAL_03

JADWAL_01:
	sbrc persiapan, 0
	rcall PERSIAPAN_JADWAL_01
	ldi temp, 0b00000100
	out PORTA, temp
	out PORTB, temp
	ldi temp, 0b00010000
	out PORTC, temp
	rcall DELAY
	rjmp CHECK_STATUS

JADWAL_02:
	sbrc persiapan, 0
	rcall PERSIAPAN_JADWAL_02
	ldi temp, 0b00010000
	out PORTA, temp
	ldi temp, 0b00000100
	out PORTB, temp
	out PORTC, temp
	rcall DELAY
	rjmp CHECK_STATUS

JADWAL_03:
	sbrc persiapan, 0
	rcall PERSIAPAN_JADWAL_03
	ldi temp, 0b00010000
	out PORTB, temp
	ldi temp, 0b00000100
	out PORTC, temp
	out PORTA, temp
	rcall DELAY
	rjmp CHECK_STATUS

PERSIAPAN_JADWAL_01:
	ldi temp, 0b00001000
	out PORTB, temp
	rcall DELAY
	clr persiapan
	ret

PERSIAPAN_JADWAL_02:
	ldi temp, 0b00001000
	out PORTC, temp
	rcall DELAY
	clr persiapan
	ret

PERSIAPAN_JADWAL_03:
	ldi temp, 0b00001000
	out PORTA, temp
	rcall DELAY
	clr persiapan
	ret

DEFENSE:
	ldi temp, 0b01100011
	out PORTA, temp
	out PORTB, temp
	out PORTC, temp
	rcall DELAY
	ldi temp, 0b00000000
	out PORTA, temp
	out PORTB, temp
	out PORTC, temp
	rcall DELAY
	rjmp CHECK_STATUS

LIBUR:
	dec count_libur
	ldi temp, 0b00010000
	out PORTA, temp
	out PORTB, temp
	out PORTC, temp
	rcall DELAY
	ldi temp, 0b00000000
	out PORTA, temp
	out PORTB, temp
	out PORTC, temp
	rcall DELAY
	rjmp CHECK_STATUS

INTERRUPT_SWITCH_JADWAL:
	sbrc count_libur, 0
	rjmp EXIT_INTERRUPT
	inc count_jadwal
	inc persiapan
	cpi count_jadwal, 3
	breq RESET
	brne EXIT_INTERRUPT

RESET:
	clr count_jadwal
	rjmp EXIT_INTERRUPT

INTERRUPT_LIBUR:
	ldi count_libur, 10
	inc libur_flag
	rjmp EXIT_INTERRUPT

INTERRUPT_DEFENSE:
	inc defense_flag
	clr count_jadwal
	sbrc defense_flag, 1
	clr defense_flag
	rjmp EXIT_INTERRUPT

EXIT_INTERRUPT:
	reti

DELAY:
; Generated by delay loop calculator
; at http://www.bretmulvey.com/avrdelay.html
;
; DELAY_CONTROL 20 000 cycles
; 2ms at 8.0 MHz

	ldi  r22, 99
	ldi  r23, 249
	
L2: 
	dec  r23
	brne L2
	dec  r22
	brne L2
	nop
	ret
